### PR TITLE
Add support for non-CKS implementation

### PR DESCRIPTION
**Pull request by scjohns**

### CODE REVIEW

**Comment by scjohns** [comment]
Change notes:

- Added cseUseCks variable
- Added cseSecretKey variable
- Updated script logic to set non-CKS user values within a single function called within #Actions section instead of directly inline within #Actions section of the script
- Added function to generate SECRET_KEY value for non-CKS use
- Updated env write function to add USE_CKS and SECRET_KEY and conditional values based on CKS usage

**Review by c3foto — COMMENTED** [review]
👍

**Review by c3foto — COMMENTED** [review]
👍

**Comment by c3foto** [comment]
Looks good sam

**Review by c3foto — APPROVED** [review]

**Pull request merged**
